services:
  - type: web
    name: yejsira
    env: docker
    plan: free
    region: frankfurt           # or closest region to you
    buildCommand: "./scripts/render-build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - fromDatabase:
          name: yejsira-db
          property: host
          envVarKey: DB_HOST
      - fromDatabase:
          name: yejsira-db
          property: user
          envVarKey: DB_USERNAME
      - fromDatabase:
          name: yejsira-db
          property: password
          envVarKey: DB_PASSWORD
      - fromDatabase:
          name: yejsira-db
          property: database
          envVarKey: DB_DATABASE
