services:
  - type: web
    name: yejsira
    runtime: php
    plan: free
    repo: https://github.com/Tsiondemsew/yejsira
    buildCommand: |
      composer install
      php artisan config:cache
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
      - key: APP_KEY
        sync: false
